### ISSUE TITLE
error  when run teleop_hand.py

### ISSUE THREAD

**Issue by dbdxnuliba** [unitreerobotics/avp_teleoperate#2]
teleop_hand.py:111: DeprecationWarning: an integer is required (got type isaacgym._bindings.linux-x86_64.gym_38.DofDriveMode).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  asset_options.default_dof_drive_mode = gymapi.DOF_MODE_POS
dof: 12
Traceback (most recent call last):
  File "teleop_hand.py", line 261, in <module>
    head_rmat, left_pose, right_pose, left_qpos, right_qpos = teleoperator.step()
  File "teleop_hand.py", line 52, in step
    rotations.quaternion_from_matrix(left_wrist_mat[:3, :3])[[1, 2, 3, 0]]])
  File "/home/rob/anaconda3/envs/tv/lib/python3.8/site-packages/pytransform3d/rotations/_conversions.py", line 1978, in quaternion_from_matrix
    R = check_matrix(R, strict_check=strict_check)
  File "/home/rob/anaconda3/envs/tv/lib/python3.8/site-packages/pytransform3d/rotations/_utils.py", line 476, in check_matrix
    raise ValueError(error_msg)
ValueError: Expected rotation matrix, but it failed the test for inversion by transposition. np.dot(R, R.T) gives array([[1., 0., 1.],
       [0., 1., 0.],
       [1., 0., 2.]])
/home/rob/anaconda3/envs/tv/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by silencht** [comment]
please pull the latest commit and try again.
